services:
#  server:
#    build:
#      context: .
#    ports:
#      - 8080:8080
#    depends_on:
#      db:
#        condition: service_healthy
#      cache:
#        condition: service_healthy


  db:
    image: postgres:17.1-alpine
    restart: always
    user: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=star-wars
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server", "--requirepass", "password", "--protected-mode", "no" ]
volumes:
  dbdata:
    driver: local
  cache:
    driver: local



